server:
  port: 8080
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
greeting-service:
  greeting: "Ciao"
  default-value: "Mondo"